import './globals.css'
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Metadata } from "next";
import { cn } from "@/lib/utils";

const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
        title: 'Create Next App',
        description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
          <html lang="en" suppressHydrationWarning>
            <body className={cn("bg-secondary", inter.className)}>
              <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
                {children}
              </ThemeProvider>
            </body>
          </html>
        </ClerkProvider>
      )
}

